=== AipNooBest/ptai-ee-tools/ptai-data-structures/src/main/resources/aiproj/schema/aiproj-legacy.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "definitions": {
    "nullable-string": {
      "type": ["string", "null"]
    },
    "nullable-integer": {
      "type": ["integer", "null"]
    },
    "nullable-boolean": {
      "type": ["boolean", "null"]
    },
    "GenericValue": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/nullable-string"
        },
        "value": {
          "$ref": "#/definitions/nullable-string"
        },
        "regexp": {
          "$ref": "#/definitions/nullable-string"
        },
        "is_regexp": {
          "type": "boolean"
        }
      },
      "required": [
        "is_regexp"
      ]
    },
    "Authentication": {
      "type": "object",
      "properties": {
        "auth_item": {
          "type": "object",
          "properties": {
            "domain": {
              "$ref": "#/definitions/nullable-string"
            },
            "credentials": {
              "type": "object",
              "properties": {
                "cookie": {
                  "$ref": "#/definitions/nullable-string"
                },
                "type": {
                  "type": "integer",
                  "description": "0 = Form, 1 = HTTP, 2 = None, 3 = Cookie"
                },
                "login": { "$ref": "#/definitions/GenericValue" },
                "password": { "$ref": "#/definitions/GenericValue" }
              },
              "required": [
                "cookie",
                "type",
                "login",
                "password"
              ]
            },
            "test_url": {
              "$ref": "#/definitions/nullable-string"
            },
            "form_url": {
              "$ref": "#/definitions/nullable-string"
            },
            "form_xpath": {
              "type": "string"
            },
            "regexp_of_success": {
              "$ref": "#/definitions/nullable-string"
            }
          },
          "required": [
            "domain",
            "credentials",
            "test_url",
            "form_url",
            "form_xpath",
            "regexp_of_success"
          ]
        }
      },
      "required": [
        "auth_item"
      ]
    },
    "ProxySettings": {
      "type": "object",
      "properties": {
        "IsEnabled": {
          "type": "boolean"
        },
        "Host": {
          "$ref": "#/definitions/nullable-string"
        },
        "Port": {
          "$ref": "#/definitions/nullable-integer"
        },
        "Type": {
          "$ref": "#/definitions/nullable-integer"
        },
        "Username": {
          "$ref": "#/definitions/nullable-string"
        },
        "Password": {
          "$ref": "#/definitions/nullable-string"
        }
      },
      "required": [
        "IsEnabled"
      ]
    },
    "Headers": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "ScanType": {
      "javaType": "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.legacy.ScanAppType",
      "type": "string",
      "enum": ["Php", "Java", "CSharp", "JavaScript", "Configuration", "Fingerprint", "PmTaint", "BlackBox"]
    }
  },
  "additionalProperties": false,
  "properties": {
    "ProjectName": {
      "title": "Project name",
      "type": "string",
      "minLength": 1
    },
    "ProgrammingLanguage": {
      "javaType": "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.legacy.ProgrammingLanguage",
      "title": "Active scanning language",
      "type": "string",
      "enum": [
        "Java",
        "CSharp",
        "VB",
        "Php",
        "JavaScript",
        "Python",
        "ObjectiveC",
        "Swift",
        "CPlusPlus",
        "Go",
        "Kotlin",
        "Sql"
      ]
    },
    "ScanAppType": {
      "title": "Comma separated list of PT AI scan engines",
      "type": "string"
    },
    "Site": {
      "title": "Website address",
      "type": "string"
    },
    "IsDownloadDependencies": {
      "description": "Download dependencies",
      "type": "boolean"
    },
    "IsUsePublicAnalysisMethod": {
      "description": "Search from available public and protected methods",
      "type": "boolean"
    },
    "CustomParameters": {
      "title": "Custom parameters",
      "description": "Custom kernel startup parameters",
      "$ref": "#/definitions/nullable-string"
    },
    "IsUnpackUserPackages": {
      "title": "Unpack custom JAR files",
      "description": "Unpack user packages for Java. Prefixes that define what JARs are to be unpacked are defined via -upp com.mycompany|com.my.company parameter in CustomParameters",
      "type": "boolean"
    },
    "UserPackagePrefixes": {
      "title": "User-defined Java package prefixes",
      "$ref": "#/definitions/nullable-string"
    },
    "JavaParameters": {
      "title": "JVM start options",
      "description": "Additional JDK run parameters",
      "$ref": "#/definitions/nullable-string"
    },
    "JavaVersion": {
      "javaType": "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.legacy.JavaVersion",
      "title": "JDK version",
      "description": "JDK version. 0 for 1.8 and 1 for 1.11",
      "type": "integer",
      "enum": [0, 1]
    },
    "ProjectType": {
      "javaType": "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.legacy.DotNetProjectType",
      "title": "Type of application",
      "description": ".NET project type",
      "type": "string",
      "enum": ["None", "Solution", "WebSite"]
    },
    "SolutionFile": {
      "title": "Solution file",
      "description": "Path to a solution or project",
      "$ref": "#/definitions/nullable-string"
    },
    "UseTaintAnalysis": {
      "title": "Use taint analysis mode of PmTaint engine",
      "type": "boolean"
    },
    "UsePmAnalysis": {
      "title": "Use pattern matching mode of PmTaint engine",
      "type": "boolean"
    },
    "UseSecurityPolicies": {
      "title": "Check AST results for security policy compliance",
      "type": "boolean"
    },
    "UseSastRules": {
      "title": "Use SAST rules",
      "type": "boolean"
    },
    "UseCustomYaraRules": {
      "title": "Use custom YARA rules",
      "type": "boolean"
    },
    "Level": {
      "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.legacy.blackbox.ScanLevel",
      "title": "Search mode",
      "type": "string",
      "enum": ["None", "Fast", "Full", "Normal"]
    },
    "ScanScope": {
      "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.legacy.blackbox.ScanScope",
      "title": "Scan scope",
      "type": "string",
      "enum": ["Domain", "Folder", "Path"]
    },
    "CustomHeaders": { "$ref": "#/definitions/Headers" },
    "Authentication": { "$ref": "#/definitions/Authentication" },
    "ProxySettings": { "$ref": "#/definitions/ProxySettings" },
    "RunAutocheckAfterScan": {
      "type": "boolean"
    },
    "AutocheckCustomHeaders": { "$ref": "#/definitions/Headers" },
    "AutocheckAuthentication": { "$ref": "#/definitions/Authentication" },
    "AutocheckProxySettings": { "$ref": "#/definitions/ProxySettings" },
    "PreprocessingTimeout": {
      "type": "integer"
    }
  },
  "required": [
    "ProjectName",
    "ProgrammingLanguage",
    "ScanAppType"
  ]
}

=== AipNooBest/ptai-ee-tools/ptai-data-structures/src/testFixtures/resources/json/scan/settings/legacy/settings.csharp.solution.none.json
{
    "ProjectName": "junit-csharp-webgoat",
    "ProgrammingLanguage": "CSharp",
    "ScanAppType": "Configuration, Csharp, PmTaint",
    "IsUsePublicAnalysisMethod": true,
    "IsDownloadDependencies": true,
    "CustomParameters": null,
    "ProjectType": "Solution",
    "UseSecurityPolicies": false,
    "UseCustomYaraRules": false,
    "UseSastRules": false
}

=== AipNooBest/ptai-ee-tools/ptai-data-structures/src/testFixtures/resources/json/scan/settings/legacy/settings.full.json
{
    "ProjectName": "WebGoat.NET",
    "ProgrammingLanguage": "Java",
    "ScanAppType": "Java, Configuration, Fingerprint, PmTaint, BlackBox",
    "Site": "https://test.ptdemo.local",
    "IsDownloadDependencies": true,
    "IsUsePublicAnalysisMethod": true,
    "CustomParameters": "--log-level=trace",
    "JavaParameters": "-Dfile.encoding=UTF-8",
    "IsUnpackUserPackages": true,
    "JavaVersion": 1,
    "PreprocessingTimeout": 60,
    "UserPackagePrefixes": "com.ptsecurity.appsec",

    "ProjectType": "Solution",
    "SolutionFile": "./WebGoat.NET.sln",

    "UseTaintAnalysis": true,
    "UsePmAnalysis": true,
    "UseSecurityPolicies": true,

    "UseCustomYaraRules": false,
    "UseSastRules": false,

    "Level": "Full",
    "ScanScope": "Domain",
    "CustomHeaders": [["custom-header", "custom-value"], ["ptai-scan", "ptai-scan-header-value"]],

    "Authentication": {
        "auth_item": {
            "domain": "ptdemo.local",
            "credentials": {
                "cookie": null,
                "cookies": null,
                "type": 0,
                "login": {
                    "name": "username",
                    "value": "admin",
                    "regexp": null,
                    "is_regexp": false
                },
                "password": {
                    "name": "password",
                    "value": "P@ssw0rd",
                    "regexp": null,
                    "is_regexp": false
                }
            },
            "test_url": "https://test.ptdemo.local",
            "form_url": "https://test.ptdemo.local/login",
            "form_xpath": "/html/body/form",
            "regexp_of_success": "Welcome"
        }
    },
    "ProxySettings": {
        "IsEnabled": true,
        "Host": "proxy.ptdemo.local",
        "Port": 3128,
        "Type": 0,
        "Username": "admin",
        "Password": "P@ssw0rd"
    },
    "RunAutocheckAfterScan": true,
    "AutocheckCustomHeaders": [["custom-header", "custom-value"], ["one-more-custom-header", "another-value"]],
    "AutocheckAuthentication": {
        "auth_item": {
            "domain": "ptdemo.local",
            "credentials": {
                "cookie": null,
                "cookies": null,
                "type": 2,
                "login": {
                    "name": "username",
                    "value": "admin",
                    "regexp": null,
                    "is_regexp": false
                },
                "password": {
                    "name": "password",
                    "value": "P@ssw0rd",
                    "regexp": null,
                    "is_regexp": false
                }
            },
            "test_url": "https://test.ptdemo.local",
            "form_url": "https://test.ptdemo.local/login",
            "form_xpath": "/html/body/form",
            "regexp_of_success": "Welcome"
        }
    },
    "AutocheckProxySettings": {
        "IsEnabled": true,
        "Host": "proxy.ptdemo.local",
        "Port": 3128,
        "Type": 0,
        "Username": "admin",
        "Password": "P@ssw0rd"
    }
}
