=== AipNooBest/ptai-ee-tools/ptai-data-structures/src/main/resources/aiproj/schema/aiproj-v1.1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "nullable-string": {
      "type": [
        "string",
        "null"
      ]
    },
    "nullable-boolean": {
      "type": [
        "boolean",
        "null"
      ]
    }
  },
  "additionalProperties": false,
  "description": "Settings for project analysis by the Application Inspector",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Version": {
      "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.Version",
      "type": "string",
      "enum": ["1.0", "1.1"]
    },
    "BlackBoxSettings": {
      "title": "black box options",
      "type": ["object", "null"],
      "description": "Black box and autocheck options",
      "additionalProperties": false,
      "properties": {
        "AdditionalHttpHeaders": {
          "title": "HTTP headers",
          "description": "Dictionary of additional HTTP headers",
          "type": ["array", "null"],
          "items": {
            "type": "object",
            "properties": {
              "Key": {
                "title": "Header",
                "type": "string"
              },
              "Value": {
                "type": "string",
                "title": "value"
              }
            }
          }
        },
        "WhiteListedAddresses": {
          "type": ["array", "null"],
          "title": "Whitelisted addresses",
          "description": "Addresses, that was added in white list",
          "items": {
            "type": "object",
            "properties": {
              "Address": {
                "title": "Address",
                "description": "Address value",
                "type": "string"
              },
              "Format": {
                "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.siteaddress.Format",
                "type": "string",
                "title": "Address format",
                "description": "Type of address",
                "enum": ["Wildcard", "ExactMatch", "RegExp"]
              }
            }
          }
        },
        "BlackListedAddresses": {
          "type": ["array", "null"],
          "title": "Blacklisted addresses",
          "description": "Addresses, that was added in black list",
          "items": {
            "type": "object",
            "properties": {
              "Address": {
                "title": "Address",
                "description": "Address value",
                "type": "string"
              },
              "Format": {
                "type": "string",
                "title": "Address format",
                "description": "Type of address",
                "enum": ["Wildcard", "ExactMatch", "RegExp"]
              }
            }
          }
        },
        "Authentication": {
          "title": "authentication options",
          "oneOf": [
            {
              "type": "object",
              "required": ["Cookie", "Type"],
              "properties": {
                "Type": {
                  "enum": ["RawCookie"]
                },
                "Cookie": {
                  "type": "object"
                }
              }
            },
            {
              "type": "object",
              "required": ["Form", "Type"],
              "properties": {
                "Type": {
                  "enum": ["Form"]
                },
                "Form": {
                  "type": "object"
                }
              }
            },
            {
              "type": "object",
              "required": ["Http", "Type"],
              "properties": {
                "Type": {
                  "enum": ["Http"]
                },
                "Http": {
                  "type": "object"
                }
              }
            },
            {
              "type": "object",
              "required": ["Type"],
              "properties": {
                "Type": {
                  "enum": ["None"]
                }
              }
            },
            {
              "type": "null"
            }
          ],
          "type": ["object", "null"],
          "description": "Authentication options",
          "additionalProperties": false,
          "properties": {
            "Cookie": {
              "type": ["object", "null"],
              "title": "Cookie options",
              "description": "Cookie authentication options",
              "required": ["Cookie", "ValidationAddress", "ValidationTemplate"],
              "additionalProperties": false,
              "properties": {
                "Cookie": {
                  "title": "cookie authentication options",
                  "description": "Cookie authentication options",
                  "type": "string"
                },
                "ValidationAddress": {
                  "title": "Validation address",
                  "description": "Verification address",
                  "type": "string"
                },
                "ValidationTemplate": {
                  "title": "Validation template",
                  "description": "String to search for",
                  "type": "string"
                }
              }
            },
            "Form": {
              "type": ["object", "null"],
              "title": "form authentication options",
              "description": "Form-based authentication options",
              "additionalProperties": false,
              "properties": {
                "FormDetection": {
                  "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.blackbox.AuthFormDetectionType",
                  "type": "string",
                  "title": "Detection",
                  "description": "Type of form authentication detection",
                  "enum": ["Auto", "Manual"]
                },
                "FormAddress": {
                  "title": "Sign-in form URL"
                },
                "FormXPath": {
                  "title": "Sign-in form XPath"
                },
                "Login": {
                  "title": "User"
                },
                "LoginKey": {
                  "title": "User identifier"
                },
                "Password": {
                  "title": "Password"
                },
                "PasswordKey": {
                  "title": "Password identifier"
                },
                "ValidationTemplate": {
                  "title": "Validation template",
                  "description": "String to search for"
                }
              },
              "anyOf": [
                {
                  "properties": {
                    "FormDetection": { "enum": ["Auto"] },
                    "FormAddress": {
                      "type": ["string"]
                    },
                    "FormXPath": {
                      "$ref": "#/definitions/nullable-string"
                    },
                    "Login": {
                      "type": "string"
                    },
                    "LoginKey": {
                      "$ref": "#/definitions/nullable-string"
                    },
                    "Password": {
                      "type": "string"
                    },
                    "PasswordKey": {
                      "$ref": "#/definitions/nullable-string"
                    },
                    "ValidationTemplate": {
                      "type": ["string"]
                    }
                  },
                  "required": [
                    "FormDetection",
                    "Login",
                    "Password",
                    "FormAddress",
                    "ValidationTemplate"
                  ]
                },
                {
                  "properties": {
                    "FormDetection": { "enum": ["Manual"] },
                    "FormAddress": {
                      "type": ["string"]
                    },
                    "FormXPath": {
                      "type": ["string"]
                    },
                    "Login": {
                      "type": "string"
                    },
                    "LoginKey": {
                      "type": ["string"]
                    },
                    "Password": {
                      "type": "string"
                    },
                    "PasswordKey": {
                      "type": ["string"]
                    },
                    "ValidationTemplate": {
                      "type": ["string"]
                    }
                  },
                  "required": [
                    "FormDetection",
                    "Login",
                    "Password",
                    "FormAddress",
                    "ValidationTemplate",
                    "LoginKey",
                    "PasswordKey",
                    "FormXPath"
                  ]
                }
              ]
            },
            "Http": {
              "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.authentication.Http",
              "title": "HTTP authentication options",
              "type": ["object", "null"],
              "description": "HTTP Basic authentication options",
              "additionalProperties": false,
              "required": ["Login", "Password", "ValidationAddress"],
              "properties": {
                "Login": {
                  "title": "User",
                  "type": "string"
                },
                "Password": {
                  "title": "Password",
                  "type": "string"
                },
                "ValidationAddress": {
                  "title": "Validation address",
                  "type": "string"
                }
              }
            },
            "Type": {
              "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.blackbox.AuthType",
              "title": "Type of authentication",
              "type": "string",
              "enum": ["Form", "Http", "RawCookie", "None"]
            }
          }
        },
        "Level": {
          "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.blackbox.ScanLevel",
          "title": "Search mode",
          "type": "string",
          "enum": ["None", "Fast", "Full", "Normal"]
        },
        "ProxySettings": {
          "type": ["object", "null"],
          "title": "proxy options",
          "description": "Proxy server settings",
          "additionalProperties": false,
          "properties": {
            "Enabled": {
              "title": "Enables",
              "type": "boolean"
            },
            "Host": {
              "title": "Address",
              "$ref": "#/definitions/nullable-string"
            },
            "Login": {
              "title": "User",
              "$ref": "#/definitions/nullable-string"
            },
            "Password": {
              "title": "Password",
              "$ref": "#/definitions/nullable-string"
            },
            "Port": {
              "title": "Port",
              "type": "integer"
            },
            "Type": {
              "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.blackbox.ProxyType",
              "title": "Type of proxy",
              "type": "string",
              "enum": ["Http", "Socks4", "Socks5"]
            }
          }
        },
        "RunAutocheckAfterScan": {
          "title": "Run autocheck",
          "description": "Autocheck vulnerabilities after scanning",
          "type": "boolean"
        },
        "ScanScope": {
          "javaType" : "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.blackbox.ScanScope",
          "title": "Scan scope",
          "type": "string",
          "enum": ["Domain", "Folder", "Path"]
        },
        "Site": {
          "title": "Website address",
          "type": "string"
        },
        "SslCheck": {
          "title": "Check ssl connection",
          "type": "boolean"
        }
      }
    },
    "CustomParameters": {
      "title": "Custom parameters",
      "description": "Custom kernel startup parameters",
      "$ref": "#/definitions/nullable-string"
    },
    "DotNetSettings": {
      "javaType": "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.DotNetSettings",
      "title": ".NET options",
      "type": ["object", "null"],
      "description": ".NET scan options",
      "additionalProperties": false,
      "properties": {
        "ProjectType": {
          "javaType": "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.DotNetProjectType",
          "title": "Type of application",
          "type": "string",
          "enum": ["None", "Solution", "WebSite"]
        },
        "SolutionFile": {
          "title": "Solution file",
          "description": "Path to a solution or project",
          "$ref": "#/definitions/nullable-string"
        }
      }
    },
    "JavaSettings": {
      "title": "Java options",
      "type": ["object", "null"],
      "description": "Java scan options",
      "additionalProperties": false,
      "properties": {
        "Parameters": {
          "title": "JVM start options",
          "$ref": "#/definitions/nullable-string"
        },
        "UnpackUserPackages": {
          "title": "Unpack custom JAR files",
          "type": "boolean"
        },
        "UserPackagePrefixes": {
          "title": "Prefixes of custom packages",
          "$ref": "#/definitions/nullable-string"
        },
        "Version": {
          "javaType": "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.JavaVersion",
          "title": "JDK version",
          "type": "string",
          "enum": ["v1_8", "v1_11"]
        }
      }
    },
    "MailingProjectSettings": {
      "type": ["object", "null"],
      "title": "mail settings",
      "description": "Report mailing options",
      "additionalProperties": false,
      "properties": {
        "Enabled": {
          "title": "Send a report by email after scanning",
          "type": "boolean"
        },
        "MailProfileName": {
          "title": "Email profile name",
          "$ref": "#/definitions/nullable-string"
        },
        "EmailRecipients": {
          "title": "List of recipients",
          "type": "array",
          "items": {
            "type": "string",
            "format": "email"
          }
        }
      },
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "Enabled": {
              "enum": [true]
            },
            "MailProfileName": {
              "type": "string",
              "minLength": 1
            },
            "EmailRecipients": {
              "type": "array",
              "minItems": 1,
              "maxItems": 10
            }
          },
          "required": ["Enabled", "MailProfileName", "EmailRecipients"]
        },
        {
          "properties": {
            "Enabled": {
              "enum": [false]
            },
            "MailProfileName": {
              "$ref": "#/definitions/nullable-string"
            },
            "EmailRecipients": {
              "type": "array",
              "minItems": 0,
              "maxItems": 10
            }
          },
          "required": ["Enabled"]
        }
      ]
    },
    "ProgrammingLanguage": {
      "javaType": "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.ProgrammingLanguage",
      "title": "Active scanning language",
      "type": "string",
      "enum": [
        "Java",
        "CSharp",
        "VB",
        "Php",
        "JavaScript",
        "Python",
        "ObjectiveC",
        "Swift",
        "CAndCPlusPlus",
        "Go",
        "Kotlin",
        "Sql"
      ]
    },
    "ProjectName": {
      "title": "Project name",
      "type": "string",
      "minLength": 1
    },
    "ScanModules": {
      "title": "Enabled modules",
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "javaType": "com.ptsecurity.appsec.ai.ee.scan.settings.aiproj.v11.ScanModule",
        "type": "string",
        "enum": [
          "Configuration",
          "Components",
          "BlackBox",
          "DataFlowAnalysis",
          "PatternMatching",
          "VulnerableSourceCode"
        ]
      }
    },
    "SkipGitIgnoreFiles": {
      "title": "Skip .gitignore files",
      "description": "Exclude from scanning the files from the .gitignore file",
      "type": "boolean"
    },
    "UsePublicAnalysisMethod": {
      "title": "Use public analysis method",
      "description": "Search from available public and protected methods",
      "type": "boolean"
    },
    "UseSastRules": {
      "title": "Use SAST rules",
      "description": "Enable SAST Analysis rules",
      "type": "boolean"
    },
    "UseCustomPmRules": {
      "title": "Use custom PM rules",
      "description": "Enable custom PM rules",
      "type": "boolean"
    },
    "UseSecurityPolicies": {
      "title": "Use security policies",
      "description": "Check for compliance with the security policy",
      "type": "boolean"
    },
    "DownloadDependencies": {
      "title": "Download dependencies",
      "$ref": "#/definitions/nullable-boolean"
    }
  },
  "required": ["ProjectName", "ProgrammingLanguage", "ScanModules"],
  "title": "aiproj",
  "type": "object"
}

=== AipNooBest/ptai-ee-tools/ptai-data-structures/src/testFixtures/resources/json/scan/settings/v11/settings.unix.solutionfile.json
{
    "$schema": "https://json.schemastore.org/aiproj-1.1.json",
    "Version": "1.1",
    "ProjectName": "ProjectName",
    "ProgrammingLanguage": "CSharp",
    "ScanModules": [
        "VulnerableSourceCode",
        "DataFlowAnalysis",
        "PatternMatching",
        "Components",
        "Configuration"
    ],
    "CustomParameters": null,
    "UseSastRules": false,
    "UseCustomPmRules": false,
    "UseSecurityPolicies": false,
    "SkipGitIgnoreFiles": false,
    "UsePublicAnalysisMethod": true,
    "DownloadDependencies": true,
    "DotNetSettings": {
        "ProjectType": "Solution",
        "SolutionFile": "/var/tmp/servername-1-workdir/70c9f648331363ce/path/to/file.sln"
    },
    "MailingProjectSettings": {
        "Enabled": false,
        "MailProfileName": null,
        "EmailRecipients": []
    }
}

=== AipNooBest/ptai-ee-tools/ptai-data-structures/src/testFixtures/resources/json/scan/settings/v11/settings.csharp.non-root.solutionfile.json
{
    "$schema": "https://json.schemastore.org/aiproj-1.1.json",
    "Version": "1.1",
    "ProjectName": "WebGoat.NET",
    "ProgrammingLanguage": "CSharp",
    "ScanModules": [
        "VulnerableSourceCode",
        "DataFlowAnalysis",
        "PatternMatching",
        "Configuration"
    ],
    "CustomParameters": null,
    "UseSastRules": false,
    "UseCustomPmRules": false,
    "UseSecurityPolicies": false,
    "SkipGitIgnoreFiles": false,
    "UsePublicAnalysisMethod": true,
    "DownloadDependencies": false,
    "DotNetSettings": {
        "ProjectType": "Solution",
        "SolutionFile": "./src/WebGoat.NET.sln"
    }
}

=== AipNooBest/ptai-ee-tools/ptai-data-structures/src/testFixtures/resources/json/scan/settings/v11/settings.full.json
{
  "$schema": "https://json.schemastore.org/aiproj-1.1.json",
  "Version": "1.1",
  "ProjectName": "WebGoat.NET",
  "ProgrammingLanguage": "Java",
  "ScanModules": [
    "VulnerableSourceCode",
    "DataFlowAnalysis",
    "PatternMatching",
    "Components",
    "Configuration",
    "BlackBox"
  ],
  "CustomParameters": "--log-level=trace",
  "UseSastRules": false,
  "UseCustomPmRules": false,
  "UseSecurityPolicies": true,
  "SkipGitIgnoreFiles": false,
  "UsePublicAnalysisMethod": true,
  "DownloadDependencies": true,
  "DotNetSettings": {
    "ProjectType": "Solution",
    "SolutionFile": "./WebGoat.NET.sln"
  },
  "JavaSettings": {
    "Parameters": "-Dfile.encoding=UTF-8",
    "UnpackUserPackages": true,
    "UserPackagePrefixes": "com.ptsecurity.appsec",
    "Version": "v1_11"
  },
  "BlackBoxSettings": {
    "Site": "https://test.ptdemo.local",
    "Level": "Full",
    "SslCheck": true,
    "ScanScope": "Domain",
    "BlackListedAddresses": [
      {
        "Format": "Wildcard",
        "Address": "https://test.ptdemo.local/admin/*"
      },
      {
        "Format": "ExactMatch",
        "Address": "https://test.ptdemo.local/setup"
      }
    ],
    "WhiteListedAddresses": [
      {
        "Format": "ExactMatch",
        "Address": "https://test.ptdemo.local/sales"
      },
      {
        "Format": "Wildcard",
        "Address": "https://test.ptdemo.local/users/*"
      }
    ],
    "AdditionalHttpHeaders": [
      {
        "Key": "custom-header",
        "Value": "custom-value"
      },
      {
        "Key": "ptai-scan",
        "Value": "ptai-scan-header-value"
      }
    ],
    "Authentication": {
      "Type": "Form",
      "Form": {
        "FormDetection": "Manual",
        "LoginKey": "username",
        "PasswordKey": "password",
        "Login": "admin",
        "Password": "P@ssw0rd",
        "FormAddress": "https://test.ptdemo.local/login",
        "FormXPath": "/html/body/form",
        "ValidationTemplate": "Welcome"
      }
    },
    "ProxySettings": {
      "Enabled": true,
      "Type": "Http",
      "Host": "proxy.ptdemo.local",
      "Port": 3128,
      "Login": "admin",
      "Password": "P@ssw0rd"
    },
    "RunAutocheckAfterScan": true
  },
  "MailingProjectSettings": {
    "Enabled": true,
    "MailProfileName": "PTDemo",
    "EmailRecipients": [
      "developer@ptdemo.local",
      "ciso@ptdemo.local"
    ]
  }
}

=== AipNooBest/ptai-ee-tools/ptai-data-structures/src/testFixtures/resources/json/scan/settings/v11/settings.php-owasp-bricks.json
{
  "$schema": "https://json.schemastore.org/aiproj-1.1.json",
  "Version": "1.1",
  "ProjectName": "junit-php-owasp-bricks",
  "ProgrammingLanguage": "Php",
  "ScanModules": [
    "VulnerableSourceCode",
    "DataFlowAnalysis",
    "PatternMatching",
    "Components",
    "Configuration"
  ],
  "CustomParameters": null,
  "UseSastRules": false,
  "UseCustomPmRules": false,
  "UseSecurityPolicies": false,
  "SkipGitIgnoreFiles": false,
  "UsePublicAnalysisMethod": false,
  "DownloadDependencies": false,
  "MailingProjectSettings": {
    "Enabled": false,
    "MailProfileName": null,
    "EmailRecipients": []
  }
}
